const lessonData = {};

lessonData["01_AntwerpDiamond.mp3"] = [{
    text: "The Antwerp Diamond Heist happened in Belgium in 2003. People call it the 'heist of the century.' The target was the Antwerp Diamond Center. This is a very secure building where many of the world's diamonds are kept. A group of Italian robbers called 'The School of Turin' planned the crime. Their leader was Leonardo Notarbartolo. They rented an office in the building so they could learn about the security. They had to get past locks, cameras, and special sensors. On the weekend, they entered the vault underground. They opened more than 100 safety deposit boxes. They stole diamonds, gold, and jewelry worth about 100 million dollars. The amazing thing is that they used no violence. They hurt nobody. They left the building quietly. The police only found them because they left some trash in a forest nearby. The leader went to prison, but most of the diamonds were never found.",
    dict: { "heist": "soygun", "century": "yüzyıl", "target": "hedef", "secure": "güvenli", "building": "bina", "world": "dünya", "diamonds": "elmaslar", "kept": "tutulur/saklanır", "robbers": "soyguncular", "called": "adlandırılan", "planned": "planladı", "crime": "suç", "leader": "lider", "rented": "kiraladı", "office": "ofis", "learn": "öğrenmek", "security": "güvenlik", "past": "geçmek", "locks": "kilitler", "cameras": "kameralar", "special": "özel", "sensors": "sensörler", "weekend": "hafta sonu", "entered": "girdiler", "vault": "kasa dairesi", "underground": "yeraltı", "opened": "açtılar", "safety deposit boxes": "kiralık kasalar", "stole": "çaldılar", "gold": "altın", "jewelry": "takı/mücevher", "worth": "değerinde", "amazing": "şaşırtıcı", "thing": "şey", "used": "kullandılar", "no": "hiç/yok", "violence": "şiddet", "hurt": "incitmek/yaralamak", "nobody": "hiç kimse", "left": "ayrıldı/bıraktı", "quietly": "sessizce", "police": "polis", "found": "buldu", "because": "çünkü", "trash": "çöp", "forest": "orman", "nearby": "yakınlarda", "prison": "hapishane", "never": "asla" },
    questions: [ {q:"Did the Antwerp Diamond Heist happen in Belgium?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the target a very secure building?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the robbers rent an office to learn about the security?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they enter the vault underground?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use no violence during the robbery?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they hurt nobody?", a_en:"Yes", a_tr:"Evet"}, {q:"Were most of the diamonds found quickly?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["02_BakerStreet.mp3"] = [{
    text: "The Baker Street robbery happened in London in 1971. It is a famous story. A group of robbers wanted to steal from a bank on Baker Street. They rented a leather goods shop two doors away from the bank. While they pretended to sell bags, they were actually digging a tunnel. They dug under the shop and under a chicken restaurant to reach the bank. They used explosives to make a hole in the floor of the vault. They did this on a weekend when the bank was closed. They emptied hundreds of safety deposit boxes. A radio operator heard them talking on walkie-talkies, but the police found nothing about which bank was being robbed. They stole about 3 million pounds. They left a message on the wall that said, 'Let's see how Sherlock Holmes solves this one.' Some people think they found secret photos of important people, but this remains unproven.",
    dict: { "robbery": "soygun", "famous": "ünlü", "story": "hikaye", "steal": "çalmak", "bank": "banka", "rented": "kiraladılar", "leather": "deri", "goods": "eşyalar/mallar", "shop": "dükkan", "doors": "kapılar", "away": "uzakta", "pretended": "numara yaptılar", "sell": "satmak", "bags": "çantalar", "actually": "aslında", "digging": "kazma", "tunnel": "tünel", "dug": "kazdılar", "under": "altında", "chicken": "tavuk", "restaurant": "restoran", "reach": "ulaşmak", "used": "kullandılar", "explosives": "patlayıcılar", "hole": "delik", "floor": "zemin", "vault": "kasa dairesi", "weekend": "hafta sonu", "closed": "kapalı", "emptied": "boşalttılar", "hundreds": "yüzlerce", "radio": "radyo", "operator": "operatör", "heard": "duydu", "talking": "konuşan", "walkie-talkies": "telsizler", "found": "buldu", "nothing": "hiçbir şey", "message": "mesaj", "wall": "duvar", "solves": "çözer", "secret": "gizli", "photos": "fotoğraflar", "important": "önemli", "remains": "kalır", "unproven": "kanıtlanmamış" },
    questions: [ {q:"Did the robbery happen in London?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they rent a leather goods shop?", a_en:"Yes", a_tr:"Evet"}, {q:"Were they actually digging a tunnel?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use explosives to make a hole in the floor?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the police find nothing about which bank was being robbed?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they steal 3 million pounds?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they leave no message on the wall?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["03_BancoCentral.mp3"] = [{
    text: "The Banco Central burglary happened in Brazil in 2005. It was one of the biggest bank robberies ever. The robbers were very smart. They rented a house near the bank and pretended to run a landscaping company. This gave them a reason to move a lot of dirt. They spent three months digging a tunnel. The tunnel was about 78 meters long and went deep under the city streets. It had lights and air conditioning. It led directly to the bank vault. On a weekend, they broke through the floor and entered the vault. They stole huge containers of money. The money weighed about 3.5 tons. They took about 160 million Brazilian reais. They used no guns and triggered no alarms. The bank employees only discovered the hole on Monday morning. The police caught some of the robbers later, but much of the money was never found.",
    dict: { "burglary": "hırsızlık/soygun", "biggest": "en büyük", "robberies": "soygunlar", "ever": "şimdiye kadar", "smart": "akıllı/zeki", "rented": "kiraladılar", "house": "ev", "near": "yakın", "pretended": "numara yaptılar", "run": "çalıştırmak/yönetmek", "landscaping": "peyzaj", "company": "şirket", "reason": "sebep/neden", "move": "taşımak", "dirt": "toprak/kir", "spent": "harcadılar", "months": "aylar", "digging": "kazma", "tunnel": "tünel", "deep": "derin", "streets": "sokaklar", "lights": "ışıklar", "air conditioning": "klima", "directly": "doğrudan", "vault": "kasa dairesi", "weekend": "hafta sonu", "broke through": "kırıp geçtiler", "floor": "zemin", "huge": "kocaman", "containers": "konteynerler", "weighed": "ağırlığındaydı", "tons": "tonlar", "used": "kullandılar", "no": "hiç/yok", "guns": "silahlar", "triggered": "tetiklediler", "alarms": "alarmlar", "employees": "çalışanlar", "discovered": "keşfettiler", "hole": "delik", "morning": "sabah", "caught": "yakaladı", "later": "daha sonra", "much": "çoğu", "never": "asla" },
    questions: [ {q:"Did the Banco Central burglary happen in Brazil?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the robbers pretend to run a landscaping company?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the tunnel have lights and air conditioning?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the money weigh about 3.5 tons?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use no guns?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they trigger no alarms?", a_en:"Yes", a_tr:"Evet"}, {q:"Was all of the money found quickly?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["04_BrinksMat.mp3"] = [{
    text: "The Brink's-Mat robbery happened in London in 1983. Six robbers broke into a warehouse near Heathrow Airport. They expected to find about 3 million pounds in cash. But when they got inside, they found something much better. They found three tons of gold bars. The gold was worth 26 million pounds. The robbers poured gasoline on the security guards and threatened to light them on fire if they provided no help. The guards opened the vault. The robbers used a forklift to move the heavy gold into their van. They escaped with the gold. The police called it 'the crime of the century.' Most of the gold was never recovered. People believe the robbers melted the gold and sold it. Some say that any gold jewelry bought in the UK after 1983 might be made from this stolen gold.",
    dict: { "robbery": "soygun", "broke into": "zorla girdiler", "warehouse": "depo", "near": "yakınında", "Airport": "Havalimanı", "expected": "beklediler", "find": "bulmak", "cash": "nakit", "inside": "içeri", "something": "bir şey", "better": "daha iyi", "tons": "tonlar", "gold": "altın", "bars": "külçeler", "worth": "değerinde", "poured": "döktüler", "gasoline": "benzin", "security": "güvenlik", "guards": "korumalar", "threatened": "tehdit ettiler", "light": "yakmak", "fire": "ateş", "provided": "sağladılar", "no": "hiç/yok", "help": "yardım", "opened": "açtılar", "vault": "kasa dairesi", "used": "kullandılar", "forklift": "forklift", "move": "taşımak", "heavy": "ağır", "van": "kamyonet", "escaped": "kaçtılar", "called": "adlandırdı", "crime": "suç", "century": "yüzyıl", "recovered": "kurtarıldı/bulundu", "believe": "inanırlar", "melted": "erittiler", "sold": "sattılar", "bought": "satın alınmış", "might": "olabilir", "stolen": "çalınmış" },
    questions: [ {q:"Did the robbers break into a warehouse?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they expect to find cash?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they find three tons of gold bars?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they threaten to light the guards on fire if they provided no help?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use a forklift to move the gold?", a_en:"Yes", a_tr:"Evet"}, {q:"Was most of the gold recovered quickly?", a_en:"No", a_tr:"Hayır"}, {q:"Do people believe the robbers melted the gold?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["05_CarltonHotel.mp3"] = [{
    text: "The Carlton Hotel heist happened in Cannes, France, in 2013. It is famous because it was very simple but huge. A man walked into the Carlton Intercontinental Hotel. He was wearing a hat and a scarf to hide his face. He carried a pistol. There was a jewelry exhibition happening in the hotel lobby. The man threatened the staff and the guards. He filled a suitcase with diamonds and watches. The whole robbery took less than one minute. He walked out of the hotel and disappeared. He stole jewelry worth about 136 million dollars. This is one of the biggest thefts of jewelry in history. The police think the robber was part of a group called the 'Pink Panthers.' They are famous jewel thieves. Despite a big investigation, the police caught nobody and found nothing.",
    dict: { "heist": "soygun", "famous": "ünlü", "simple": "basit", "huge": "büyük", "walked": "yürüdü", "wearing": "giyen", "hat": "şapka", "scarf": "atkı", "hide": "saklamak/gizlemek", "face": "yüz", "carried": "taşıdı", "pistol": "tabanca", "jewelry": "takı", "exhibition": "sergi", "happening": "gerçekleşen", "lobby": "lobi", "threatened": "tehdit etti", "staff": "personel", "guards": "korumalar", "filled": "doldurdu", "suitcase": "bavul", "diamonds": "elmaslar", "watches": "saatler", "whole": "bütün", "robbery": "soygun", "less than": "daha az", "minute": "dakika", "disappeared": "kayboldu", "stole": "çaldı", "worth": "değerinde", "thefts": "hırsızlıklar", "history": "tarih", "think": "düşünüyor", "part": "parça/üye", "group": "grup", "called": "adlandırılan", "thieves": "hırsızlar", "Despite": "rağmen", "investigation": "soruşturma", "caught": "yakaladı", "nobody": "hiç kimse", "found": "buldu", "nothing": "hiçbir şey" },
    questions: [ {q:"Did the heist happen in France?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the robbery very simple but huge?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the man wear a hat and a scarf to hide his face?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the whole robbery take more than an hour?", a_en:"No", a_tr:"Hayır"}, {q:"Did he fill a suitcase with diamonds and watches?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the police think he was part of the Pink Panthers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the police catch nobody and find nothing?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_CentralBankIraq.mp3"] = [{
    text: "The Central Bank of Iraq robbery happened in Baghdad in 2003. It occurred right before the United States invaded Iraq. This was not a normal robbery with masks and guns. It was ordered by the dictator, Saddam Hussein. He sent his son, Qusay, to the bank with a handwritten note. The note said that the money was needed to protect the country from the invaders. The bank workers were unable to say no to the dictator's son. They loaded boxes of money into three large trucks. They took about 1 billion dollars in cash. This is the largest bank robbery in history. A lot of the money was US dollars. Later, American soldiers found about 650 million dollars hidden in the walls of one of Saddam's palaces. However, hundreds of millions of dollars are still missing.",
    dict: { "Central": "Merkez", "Bank": "Banka", "robbery": "soygun", "occurred": "meydana geldi", "right before": "hemen önce", "invaded": "işgal etti", "normal": "normal", "masks": "maskeler", "guns": "silahlar", "ordered": "emredildi", "dictator": "diktatör", "sent": "gönderdi", "son": "oğul", "handwritten": "el yazısı", "note": "not", "needed": "gerekli", "protect": "korumak", "country": "ülke", "invaders": "işgalciler", "workers": "işçiler", "unable": "yapamayan/aciz", "say no": "hayır demek", "loaded": "yüklediler", "boxes": "kutular", "money": "para", "large": "büyük", "trucks": "kamyonlar", "cash": "nakit", "largest": "en büyük", "history": "tarih", "Later": "daha sonra", "soldiers": "askerler", "found": "buldu", "hidden": "saklı", "walls": "duvarlar", "palaces": "saraylar", "However": "ancak", "hundreds": "yüzlerce", "millions": "milyonlar", "still": "hala", "missing": "kayıp" },
    questions: [ {q:"Did the robbery occur before the US invaded Iraq?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it ordered by Saddam Hussein?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he send his son with a handwritten note?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the bank workers unable to say no?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they load the money into small cars?", a_en:"No", a_tr:"Hayır"}, {q:"Did they take about 1 billion dollars?", a_en:"Yes", a_tr:"Evet"}, {q:"Are hundreds of millions of dollars still missing?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["07_CityBonds.mp3"] = [{
    text: "The City Bonds robbery happened in London in 1990. A courier named John Goddard was walking down a quiet street. He was carrying a briefcase. Inside the briefcase were treasury bills and certificates of deposit. These are like paper money used by banks. They were worth 292 million pounds. A robber approached him and held a knife to his throat. The robber took the briefcase and ran away. This is one of the biggest muggings in history. The police found out that the robbery was planned by a man named Keith Collins. The police worked with the FBI in America to catch the criminals. They pretended to be shady businessmen who wanted to buy the stolen bonds. They caught the gang when they tried to sell the paper money. Most of the bonds were recovered, but it showed how dangerous carrying such valuable papers can be.",
    dict: { "Bonds": "Tahviller/Bonolar", "robbery": "soygun", "courier": "kurye", "named": "adında", "walking": "yürüyen", "quiet": "sessiz", "street": "sokak", "carrying": "taşıyan", "briefcase": "evrak çantası", "Inside": "içinde", "treasury bills": "hazine bonoları", "certificates": "sertifikalar", "deposit": "mevduat", "paper": "kağıt", "used": "kullanılan", "worth": "değerinde", "robber": "soyguncu", "approached": "yaklaştı", "held": "tuttu", "knife": "bıçak", "throat": "boğaz", "took": "aldı", "ran away": "kaçtı", "biggest": "en büyük", "muggings": "gasp", "history": "tarih", "found out": "öğrendi/ortaya çıkardı", "planned": "planlanmış", "worked": "çalıştı", "catch": "yakalamak", "criminals": "suçlular", "pretended": "numara yaptılar", "shady": "şüpheli/karanlık", "businessmen": "iş adamları", "wanted": "isteyen", "buy": "satın almak", "stolen": "çalınmış", "gang": "çete", "tried": "denediler", "sell": "satmak", "recovered": "bulundu/kurtarıldı", "showed": "gösterdi", "dangerous": "tehlikeli", "valuable": "değerli", "papers": "kağıtlar" },
    questions: [ {q:"Was the courier carrying a briefcase?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the bonds inside worth 292 million pounds?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the robber hold a knife to his throat?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the police catch the gang immediately?", a_en:"No", a_tr:"Hayır"}, {q:"Did the police work with the FBI?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they pretend to be shady businessmen?", a_en:"Yes", a_tr:"Evet"}, {q:"Were most of the bonds recovered?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_DarEsSalaam.mp3"] = [{
    text: "The Dar Es Salaam Bank heist happened in Baghdad, Iraq, in 2007. The bank employees came to work in the morning and found the front door was unlocked. When they went inside, they saw that the vault was open and empty. Three guards who worked at the bank were missing. They had stolen about 282 million dollars in cash. This was a huge amount of money. The guards waited until everyone left the bank the night before. Then, they loaded the money into cars and drove away. Because the country was in a war, there were many checkpoints on the roads. Some people think the guards must have had help from the police or soldiers to move so much money with no interruptions. The money and the guards were never found. It is one of the biggest unsolved mysteries in Iraq.",
    dict: { "heist": "soygun", "employees": "çalışanlar", "came": "geldiler", "morning": "sabah", "found": "buldular", "front": "ön", "door": "kapı", "unlocked": "kilitsiz", "inside": "içeri", "saw": "gördüler", "vault": "kasa dairesi", "open": "açık", "empty": "boş", "guards": "korumalar", "worked": "çalışan", "missing": "kayıp", "stolen": "çalmış", "cash": "nakit", "huge": "kocaman", "amount": "miktar", "money": "para", "waited": "beklediler", "until": "kadar", "everyone": "herkes", "left": "ayrıldı", "night": "gece", "loaded": "yüklediler", "cars": "arabalar", "drove away": "arabayla uzaklaştılar", "Because": "çünkü", "country": "ülke", "war": "savaş", "checkpoints": "kontrol noktaları", "roads": "yollar", "think": "düşünüyor", "help": "yardım", "police": "polis", "soldiers": "askerler", "move": "taşımak", "no": "hiç/yok", "interruptions": "kesintiler", "never": "asla", "biggest": "en büyük", "unsolved": "çözülmemiş", "mysteries": "gizemler" },
    questions: [ {q:"Did the employees find the front door unlocked?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the vault open and empty?", a_en:"Yes", a_tr:"Evet"}, {q:"Were three guards missing?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they steal 5 million dollars?", a_en:"No", a_tr:"Hayır"}, {q:"Did they wait until everyone left the bank?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they move the money with no interruptions?", a_en:"Yes", a_tr:"Evet"}, {q:"Is this an unsolved mystery in Iraq?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["09_DunbarArmored.mp3"] = [{
    text: "The Dunbar Armored robbery happened in Los Angeles in 1997. It is the largest cash robbery in the United States. The mastermind was a man named Allen Pace. He worked as a safety inspector for the Dunbar company. This meant he knew everything about the cameras and the alarms. He was fired from his job, so he wanted revenge. He recruited five friends. They entered the depot on a Friday night. They used Pace's keys to get in. They waited for the guards to take a lunch break. They rushed in and tied up the guards. They loaded 18.9 million dollars into a U-Haul truck. They knew exactly which bags had the most money. They escaped and hid the money. They almost got away with it, but one of the robbers gave a stack of cash to a friend with the original money straps still on it. The police traced it back to them and arrested the gang.",
    dict: { "Armored": "Zırhlı", "robbery": "soygun", "largest": "en büyük", "cash": "nakit", "mastermind": "beyin/fikir babası", "named": "adında", "worked": "çalıştı", "safety": "güvenlik", "inspector": "müfettiş", "company": "şirket", "meant": "anlamına geliyordu", "knew": "biliyordu", "everything": "her şey", "cameras": "kameralar", "alarms": "alarmlar", "fired": "kovuldu", "wanted": "istedi", "revenge": "intikam", "recruited": "işe aldı/ikna etti", "friends": "arkadaşlar", "entered": "girdiler", "depot": "depo", "night": "gece", "keys": "anahtarlar", "waited": "beklediler", "guards": "korumalar", "lunch": "öğle yemeği", "break": "mola", "rushed in": "içeri daldılar", "tied up": "bağladılar", "loaded": "yüklediler", "truck": "kamyon", "exactly": "kesinlikle", "bags": "çantalar", "most": "en çok", "escaped": "kaçtılar", "hid": "sakladılar", "almost": "neredeyse", "got away": "kurtuldular", "stack": "yığın/deste", "friend": "arkadaş", "original": "orijinal", "straps": "kayışlar/bantlar", "traced": "izini sürdü", "arrested": "tutukladı", "gang": "çete" },
    questions: [ {q:"Is it the largest cash robbery in the United States?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Allen Pace work as a safety inspector?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he want revenge because he was fired?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they enter the depot on a Sunday morning?", a_en:"No", a_tr:"Hayır"}, {q:"Did they wait for the guards to take a break?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they know exactly which bags had the most money?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a money strap help the police trace them?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_GreatBrinks.mp3"] = [{
    text: "The Great Brink's Robbery happened in Boston in 1950. At that time, it was the biggest robbery in America. A gang of 11 men planned the crime. They watched the Brink's building for 18 months. They learned when the money trucks arrived. They even stole the keys to make copies. On the night of the robbery, they wore masks and uniforms that looked like Brink's employees. They wore special rubber shoes so they made no noise. They surprised the guards and tied them up. They stole more than 2 million dollars. They disappeared into the night. The police looked for them for a long time but found nothing. The robbers almost succeeded. But years later, one of the members got angry with the others. He told the police everything. The police arrested the gang just a few days before the time limit for the crime ran out.",
    dict: { "Great": "Büyük", "Robbery": "Soygun", "biggest": "en büyük", "gang": "çete", "men": "adamlar", "planned": "planladı", "crime": "suç", "watched": "izlediler", "building": "bina", "months": "aylar", "learned": "öğrendiler", "money": "para", "trucks": "kamyonlar", "arrived": "vardı/geldi", "stole": "çaldılar", "keys": "anahtarlar", "copies": "kopyalar", "night": "gece", "wore": "giydiler", "masks": "maskeler", "uniforms": "üniformalar", "employees": "çalışanlar", "special": "özel", "rubber": "kauçuk/lastik", "shoes": "ayakkabılar", "no": "hiç/yok", "noise": "gürültü", "surprised": "şaşırttılar", "guards": "korumalar", "tied up": "bağladılar", "disappeared": "kayboldular", "police": "polis", "looked for": "aradılar", "found": "buldular", "nothing": "hiçbir şey", "almost": "neredeyse", "succeeded": "başardılar", "years": "yıllar", "later": "daha sonra", "members": "üyeler", "angry": "öfkeli", "told": "anlattı", "everything": "her şey", "arrested": "tutukladı", "few": "birkaç", "days": "günler", "limit": "sınır", "ran out": "tükendi/bitti" },
    questions: [ {q:"Was it the biggest robbery in America at that time?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they watch the building for 18 months?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they wear uniforms that looked like employees?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they wear special rubber shoes to make no noise?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the police find all the evidence immediately?", a_en:"No", a_tr:"Hayır"}, {q:"Did one member get angry and tell the police everything?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the police arrest them just before the time limit ran out?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["11_GreatTrain.mp3"] = [{
    text: "The Great Train Robbery happened in 1963. A gang of 15 men stopped a Royal Mail train traveling to London. The train was carrying a lot of old money to be destroyed. The leader was Bruce Reynolds. They changed the railway signals to red to make the train stop. They attacked the train and hit the driver. They forced the staff to open the carriages. They moved 120 bags of money to their trucks. They stole 2.6 million pounds, which is a huge amount today. They hid at a farm nearby. They played the game Monopoly with the real money while they waited. The police found the farm later and found fingerprints on the Monopoly board. This helped them catch the gang. Some robbers, like Ronnie Biggs, escaped from prison and lived in other countries for many years before returning to jail.",
    dict: { "Great": "Büyük", "Train": "Tren", "Robbery": "Soygun", "gang": "çete", "stopped": "durdurdu", "Royal Mail": "Kraliyet Postası", "traveling": "seyahat eden", "carrying": "taşıyan", "old": "eski", "money": "para", "destroyed": "yok edilecek", "leader": "lider", "changed": "değiştirdiler", "railway": "demiryolu", "signals": "sinyaller", "red": "kırmızı", "make": "yapmak", "attacked": "saldırdılar", "hit": "vurdular", "driver": "sürücü", "forced": "zorladılar", "staff": "personel", "open": "açmak", "carriages": "vagonlar", "moved": "taşıdılar", "bags": "çantalar", "trucks": "kamyonlar", "stole": "çaldılar", "huge": "kocaman", "amount": "miktar", "hid": "saklandılar", "farm": "çiftlik", "nearby": "yakınlarda", "played": "oynadılar", "game": "oyun", "real": "gerçek", "waited": "beklediler", "police": "polis", "found": "buldu", "fingerprints": "parmak izleri", "board": "tahta", "helped": "yardım etti", "catch": "yakalamak", "escaped": "kaçtı", "prison": "hapishane", "lived": "yaşadı", "countries": "ülkeler", "returning": "dönmeden", "jail": "hapishane" },
    questions: [ {q:"Did the gang stop a Royal Mail train?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the train carrying old money to be destroyed?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they change the railway signals to red?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they hide in a big city hotel?", a_en:"No", a_tr:"Hayır"}, {q:"Did they play Monopoly with the real money?", a_en:"Yes", a_tr:"Evet"}, {q:"Did fingerprints on the board help the police?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Ronnie Biggs escape from prison?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["12_HarryWinston.mp3"] = [{
    text: "The Harry Winston Heist happened in Paris in 2008. Four men entered the famous Harry Winston jewelry store. Three of them were wearing wigs and dresses. They were dressed as women. They called themselves the 'Pink Panthers.' They had guns and grenades. They knew the names of some of the employees. They forced the staff to open the storage cases. In less than 20 minutes, they filled their bags with diamonds, rubies, and emeralds. They stole jewelry worth about 100 million dollars. They walked out of the store and drove away. The police said it was a very professional job. A year later, the police found some of the jewelry hidden in a drainpipe at a house in Paris. They arrested 25 people connected to the crime. It is considered one of the boldest robberies in French history.",
    dict: { "Heist": "Soygun", "entered": "girdiler", "famous": "ünlü", "jewelry": "takı/mücevher", "store": "mağaza", "wearing": "giyen", "wigs": "peruklar", "dresses": "elbiseler", "women": "kadınlar", "called": "adlandırdılar", "themselves": "kendilerini", "guns": "silahlar", "grenades": "el bombaları", "knew": "biliyordu", "names": "isimler", "employees": "çalışanlar", "forced": "zorladılar", "staff": "personel", "open": "açmak", "storage cases": "saklama kasaları", "less than": "daha az", "minutes": "dakikalar", "filled": "doldurdular", "bags": "çantalar", "diamonds": "elmaslar", "rubies": "yakutlar", "emeralds": "zümrütler", "stole": "çaldılar", "worth": "değerinde", "walked out": "dışarı çıktılar", "drove away": "arabayla uzaklaştılar", "police": "polis", "professional": "profesyonel", "job": "iş", "year": "yıl", "later": "sonra", "found": "buldu", "hidden": "saklı", "drainpipe": "su borusu", "house": "ev", "arrested": "tutukladılar", "connected": "bağlantılı", "crime": "suç", "considered": "kabul edilir", "boldest": "en cesur", "robberies": "soygunlar", "history": "tarih" },
    questions: [ {q:"Did the heist happen in Paris?", a_en:"Yes", a_tr:"Evet"}, {q:"Were three of the men dressed as women?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they call themselves the Pink Panthers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use only knives?", a_en:"No", a_tr:"Hayır"}, {q:"Did the robbery take less than 20 minutes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the police say it was a professional job?", a_en:"Yes", a_tr:"Evet"}, {q:"Was some jewelry found hidden in a drainpipe?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_HattonGarden.mp3"] = [{
    text: "The Hatton Garden heist happened in London in 2015. It is a famous story because the robbers were old men. Most of them were over 60 or 70 years old. People called them the 'Grandpa Gang.' They targeted a safe deposit company in the jewelry district. They planned the robbery for the Easter holiday weekend. The business was closed for four days. They entered the building through an elevator shaft. They used a heavy drill to make a hole in the thick concrete wall of the vault. They stole gold, diamonds, and cash worth about 14 million pounds. They thought they were safe, but the police found them by watching street cameras. The police recorded them talking about the crime in their cars. The old men were arrested and sent to prison. It was the biggest burglary in English legal history.",
    dict: { "heist": "soygun", "famous": "ünlü", "story": "hikaye", "because": "çünkü", "robbers": "soyguncular", "old": "yaşlı", "men": "adamlar", "called": "adlandırdı", "Gang": "Çete", "targeted": "hedef aldılar", "safe deposit": "kiralık kasa", "company": "şirket", "jewelry": "mücevher", "district": "bölge", "planned": "planladılar", "robbery": "soygun", "Easter": "Paskalya", "holiday": "tatil", "weekend": "hafta sonu", "closed": "kapalı", "entered": "girdiler", "building": "bina", "through": "aracılığıyla/içinden", "elevator": "asansör", "shaft": "boşluk", "used": "kullandılar", "heavy": "ağır", "drill": "matkap", "make": "yapmak", "hole": "delik", "thick": "kalın", "concrete": "beton", "wall": "duvar", "vault": "kasa dairesi", "stole": "çaldılar", "gold": "altın", "diamonds": "elmaslar", "cash": "nakit", "worth": "değerinde", "thought": "düşündüler", "safe": "güvenli", "police": "polis", "found": "buldu", "watching": "izleyerek", "street": "sokak", "cameras": "kameralar", "recorded": "kaydetti", "talking": "konuşurken", "crime": "suç", "cars": "arabalar", "arrested": "tutuklandı", "prison": "hapishane", "biggest": "en büyük", "burglary": "hırsızlık", "legal": "yasal", "history": "tarih" },
    questions: [ {q:"Were the robbers mostly old men?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people call them the 'Grandpa Gang'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they plan the robbery for the Easter holiday?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they enter the building through the front door?", a_en:"No", a_tr:"Hayır"}, {q:"Did they use a heavy drill to make a hole?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the police find them by watching street cameras?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the old men sent to prison?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["14_IsabellaStewart.mp3"] = [{
    text: "The Isabella Stewart Gardner Museum theft happened in Boston in 1990. It is the biggest art heist in history. Two men dressed as police officers came to the museum late at night. They told the guards they were there to help with a disturbance. The young guards let them in. The fake police officers tied up the guards. They spent 81 minutes inside the museum. They cut famous paintings out of their frames. They stole 13 pieces of art, including works by Rembrandt and Vermeer. The value of the art is about 500 million dollars. The thieves took the video tapes and left. The frames still hang empty on the walls today. The FBI has searched for more than 30 years, but the art remains unfound and the thieves remain uncaught.",
    dict: { "theft": "hırsızlık", "biggest": "en büyük", "art": "sanat", "heist": "soygun", "history": "tarih", "dressed as": "gibi giyinmiş", "police officers": "polis memurları", "came": "geldiler", "museum": "müze", "late": "geç", "night": "gece", "told": "söylediler", "guards": "korumalar", "help": "yardım etmek", "disturbance": "kargaşa/rahatsızlık", "young": "genç", "let in": "içeri aldılar", "fake": "sahte", "tied up": "bağladılar", "spent": "harcadılar/geçirdiler", "minutes": "dakikalar", "inside": "içinde", "cut": "kestiler", "famous": "ünlü", "paintings": "tablolar", "frames": "çerçeveler", "stole": "çaldılar", "pieces": "parçalar", "including": "dahil olmak üzere", "works": "eserler", "value": "değer", "thieves": "hırsızlar", "took": "aldılar", "video tapes": "video kasetleri", "left": "ayrıldılar", "still": "hala", "hang": "asılı durmak", "empty": "boş", "walls": "duvarlar", "today": "bugün", "searched": "aradılar", "years": "yıllar", "remains": "kalır", "unfound": "bulunamamış", "uncaught": "yakalanmamış" },
    questions: [ {q:"Is it the biggest art heist in history?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the men dress as police officers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they tell the guards they wanted to steal art?", a_en:"No", a_tr:"Hayır"}, {q:"Did they cut famous paintings out of their frames?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they steal 13 pieces of art?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the frames still hang empty today?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the art remain unfound?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["15_Knightsbridge.mp3"] = [{
    text: "The Knightsbridge Security Depot robbery happened in London in 1987. A man named Valerio Viccei led the robbery. He was a famous Italian criminal. He went into the bank and asked to rent a safety deposit box. He was led into the vault. Suddenly, he pulled out a gun and subdued the manager. His friends entered the bank and put a sign on the door that said 'Closed.' They let in more accomplices. They broke open the deposit boxes. They stole about 60 million pounds in cash and jewelry. Viccei escaped to South America. However, he made a mistake. He came back to England to get his favorite car, a Ferrari. The police were waiting for him. They arrested him and sent him to prison. He wrote a book about his life as a robber.",
    dict: { "Security": "Güvenlik", "Depot": "Depo", "robbery": "soygun", "named": "adında", "led": "yönetti", "famous": "ünlü", "criminal": "suçlu", "went": "gitti", "bank": "banka", "asked": "istedi/sordu", "rent": "kiralamak", "safety deposit box": "kiralık kasa", "vault": "kasa dairesi", "Suddenly": "aniden", "pulled out": "çıkardı", "gun": "silah", "subdued": "etkisiz hale getirdi", "manager": "müdür", "friends": "arkadaşlar", "entered": "girdiler", "put": "koydular", "sign": "tabela/işaret", "door": "kapı", "Closed": "Kapalı", "let in": "içeri aldılar", "more": "daha fazla", "accomplices": "suç ortakları", "broke open": "kırarak açtılar", "stole": "çaldılar", "cash": "nakit", "jewelry": "takı", "escaped": "kaçtı", "South America": "Güney Amerika", "However": "ancak", "made": "yaptı", "mistake": "hata", "came back": "geri döndü", "favorite": "favori", "car": "araba", "police": "polis", "waiting": "bekleyen", "arrested": "tutukladılar", "sent": "gönderdiler", "prison": "hapishane", "wrote": "yazdı", "book": "kitap", "life": "hayat", "robber": "soyguncu" },
    questions: [ {q:"Did Valerio Viccei lead the robbery?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he ask to rent a safety deposit box?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he pull out a gun inside the vault?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they put a sign on the door that said 'Open'?", a_en:"No", a_tr:"Hayır"}, {q:"Did Viccei escape to South America at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he come back to England to get his Ferrari?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the police arrest him when he came back?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["16_LufthansaHeist.mp3"] = [{
    text: "The Lufthansa Heist happened in New York in 1978. It took place at the airport. A worker at the airport owed money to the mob, so he told them about money flying in from Germany. The heist was planned by Jimmy Burke, a powerful criminal. A group of masked men arrived in a van late at night. They captured the employees and forced the manager to open the vault. They stole about 5 million dollars in cash and jewelry. It was the largest cash robbery in America at that time. This story is famous because of the movie 'Goodfellas.' After the robbery, Jimmy Burke was afraid the others would talk to the police. He ordered the murder of almost everyone involved in the crime. Because of this, very little of the money was ever recovered.",
    dict: { "Heist": "Soygun", "took place": "gerçekleşti", "airport": "havalimanı", "worker": "işçi", "owed": "borçluydu", "money": "para", "mob": "mafya", "told": "söyledi", "flying": "uçan/gelen", "planned": "planlandı", "powerful": "güçlü", "criminal": "suçlu", "group": "grup", "masked": "maskeli", "men": "adamlar", "arrived": "vardı/geldi", "van": "kamyonet", "late": "geç", "night": "gece", "captured": "yakaladılar", "employees": "çalışanlar", "forced": "zorladılar", "manager": "müdür", "open": "açmak", "vault": "kasa dairesi", "stole": "çaldılar", "cash": "nakit", "jewelry": "takı", "largest": "en büyük", "robbery": "soygun", "time": "zaman", "story": "hikaye", "famous": "ünlü", "movie": "film", "After": "sonra", "afraid": "korkmuş", "talk": "konuşmak", "police": "polis", "ordered": "emretti", "murder": "cinayet", "almost": "neredeyse", "everyone": "herkes", "involved": "karışmış", "crime": "suç", "Because": "çünkü", "very little": "çok az", "ever": "hiç", "recovered": "kurtarıldı/bulundu" },
    questions: [ {q:"Did the heist take place at the airport?", a_en:"Yes", a_tr:"Evet"}, {q:"Did an airport worker owe money to the mob?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the heist planned by Jimmy Burke?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they force the manager to open the vault?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Jimmy Burke give everyone a lot of money after the robbery?", a_en:"No", a_tr:"Hayır"}, {q:"Did he order the murder of almost everyone involved?", a_en:"Yes", a_tr:"Evet"}, {q:"Was very little of the money ever recovered?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["17_MillenniumDome.mp3"] = [{
    text: "The Millennium Dome raid happened in London in 2000. A gang planned to steal a collection of very rare diamonds called the Millennium Star. The diamonds were on display at the Millennium Dome exhibition. The robbers used a bulldozer to smash through the wall of the Dome. They threw smoke bombs to confuse the guards. They planned to escape on a speedboat on the river. However, the police already knew about the plan. They were waiting for the robbers. Some police officers were dressed as cleaners and tourists. As soon as the robbers broke the glass case, the police attacked. They arrested the gang immediately. The diamonds in the case were actually fake replicas. The real diamonds had been moved to a safe place. The robbers were caught with nothing.",
    dict: { "raid": "baskın", "gang": "çete", "planned": "planladı", "steal": "çalmak", "collection": "koleksiyon", "rare": "nadir", "diamonds": "elmaslar", "called": "adlandırılan", "Star": "Yıldız", "display": "sergi", "exhibition": "sergi", "robbers": "soyguncular", "used": "kullandılar", "bulldozer": "dozer", "smash": "parçalamak", "through": "içinden", "wall": "duvar", "threw": "attılar", "smoke": "duman", "bombs": "bombalar", "confuse": "kafa karıştırmak", "guards": "korumalar", "escape": "kaçmak", "speedboat": "sürat teknesi", "river": "nehir", "However": "ancak", "police": "polis", "already": "zaten", "knew": "biliyordu", "plan": "plan", "waiting": "bekleyen", "officers": "memurlar", "dressed": "giyinmiş", "cleaners": "temizlikçiler", "tourists": "turistler", "broke": "kırdılar", "glass": "cam", "case": "kasa/kutu", "attacked": "saldırdılar", "arrested": "tutukladılar", "immediately": "derhal", "actually": "aslında", "fake": "sahte", "replicas": "kopyalar", "real": "gerçek", "moved": "taşınmıştı", "safe": "güvenli", "place": "yer", "caught": "yakalandı", "nothing": "hiçbir şey" },
    questions: [ {q:"Did a gang plan to steal the Millennium Star diamonds?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use a bulldozer to smash the wall?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they throw smoke bombs to confuse the guards?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the police know nothing about the plan?", a_en:"No", a_tr:"Hayır"}, {q:"Were some police dressed as cleaners and tourists?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the diamonds in the case fake replicas?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the robbers caught with nothing?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["18_NorthernBank.mp3"] = [{
    text: "The Northern Bank robbery happened in Belfast, Northern Ireland, in 2004. It was a very well-planned crime. A group of men went to the homes of two bank managers. They took the managers' families as hostages. They told the managers to go to work the next day and act normal. If they provided no help, their families would be killed. The managers went to the bank and let the robbers in after it closed. The robbers loaded 26.5 million pounds into a van. They drove away and released the families unharmed. The police believe the robbery was done by the IRA, a paramilitary group. The robbery caused a big problem because the bank had to change all its paper money to stop the robbers from spending the stolen cash.",
    dict: { "robbery": "soygun", "Northern": "Kuzey", "well-planned": "iyi planlanmış", "crime": "suç", "group": "grup", "men": "adamlar", "went": "gittiler", "homes": "evler", "managers": "müdürler", "took": "aldılar", "families": "aileler", "hostages": "rehineler", "told": "söylediler", "work": "iş", "next": "sonraki", "day": "gün", "act": "davranmak", "normal": "normal", "provided": "sağladılar", "no": "hiç/yok", "help": "yardım", "killed": "öldürülecek", "bank": "banka", "let in": "içeri aldılar", "after": "sonra", "closed": "kapandı", "robbers": "soyguncular", "loaded": "yüklediler", "van": "kamyonet", "drove away": "arabayla uzaklaştılar", "released": "serbest bıraktılar", "unharmed": "zarar görmemiş", "police": "polis", "believe": "inanıyor", "done": "yapıldı", "paramilitary": "yarı askeri", "caused": "sebep oldu", "problem": "sorun", "change": "değiştirmek", "paper": "kağıt", "money": "para", "stop": "durdurmak", "spending": "harcama", "stolen": "çalınmış", "cash": "nakit" },
    questions: [ {q:"Was it a very well-planned crime?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the robbers take the managers' families as hostages?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they tell the managers to act normal at work?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the robbers kill the families?", a_en:"No", a_tr:"Hayır"}, {q:"Did they load 26.5 million pounds into a van?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the police believe the IRA did the robbery?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the bank have to change all its paper money?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["19_PierreHotel.mp3"] = [{
    text: "The Pierre Hotel robbery happened in New York City in 1972. It was organized by a man named Samuel Nalo. He had a team of eight robbers. They arrived at the luxury hotel in a limousine. They wore tuxedos and fake beards. They pretended to be guests. Once inside, they took control of the lobby. They handcuffed the staff and guests. They knew that many rich people kept jewelry in the hotel's safe deposit boxes. They forced the night manager to open the boxes. They stole cash and jewelry worth about 27 million dollars. It was the largest hotel robbery in history. The robbers escaped, but they had internal fights about splitting the money. Most of them were eventually caught by the FBI or killed by other criminals.",
    dict: { "robbery": "soygun", "organized": "organize edildi", "named": "adında", "team": "ekip", "robbers": "soyguncular", "arrived": "vardılar/geldiler", "luxury": "lüks", "hotel": "otel", "limousine": "limuzin", "wore": "giydiler", "tuxedos": "smokinler", "fake": "sahte", "beards": "sakallar", "pretended": "numara yaptılar", "guests": "misafirler", "inside": "içeri", "took control": "kontrolü ele aldılar", "lobby": "lobi", "handcuffed": "kelepçelediler", "staff": "personel", "knew": "biliyorlardı", "rich": "zengin", "kept": "tuttu/sakladı", "jewelry": "takı", "safe deposit boxes": "kiralık kasalar", "forced": "zorladılar", "night": "gece", "manager": "müdür", "open": "açmak", "stole": "çaldılar", "cash": "nakit", "worth": "değerinde", "largest": "en büyük", "history": "tarih", "escaped": "kaçtılar", "internal": "iç", "fights": "kavgalar", "splitting": "bölüşme", "money": "para", "eventually": "sonunda", "caught": "yakalandı", "killed": "öldürüldü", "other": "diğer", "criminals": "suçlular" },
    questions: [ {q:"Was the robbery organized by Samuel Nalo?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the robbers arrive in a limousine?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they wear tuxedos and fake beards?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they pretend to be police officers?", a_en:"No", a_tr:"Hayır"}, {q:"Did they handcuff the staff and guests?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they have internal fights about splitting the money?", a_en:"Yes", a_tr:"Evet"}, {q:"Were most of them eventually caught or killed?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_SecuritasDepot.mp3"] = [{
    text: "The Securitas Depot robbery happened in England in 2006. It was the largest cash robbery in British history. The robbers kidnapped the manager of the depot. They pulled his car over by pretending to be police officers. At the same time, another group kidnapped his wife and child at their home. They told the manager they would hurt his family if he provided no help. They took him to the depot at night. He opened the gates for them. The robbers tied up 14 employees. They loaded about 53 million pounds in cash into a truck. This money was very heavy. They left the hostages locked in cages and escaped. The police found that the money had been split up. Some people were arrested, but much of the money is still missing.",
    dict: { "Depot": "Depo", "robbery": "soygun", "largest": "en büyük", "cash": "nakit", "history": "tarih", "robbers": "soyguncular", "kidnapped": "kaçırdılar", "manager": "müdür", "pulled over": "kenara çektirdiler (araç)", "pretending": "numara yaparak", "police officers": "polis memurları", "same": "aynı", "time": "zaman", "another": "başka", "group": "grup", "wife": "eş", "child": "çocuk", "home": "ev", "told": "söylediler", "hurt": "incitmek/zarar vermek", "family": "aile", "provided": "sağladı", "no": "hiç/yok", "help": "yardım", "took": "götürdüler", "night": "gece", "opened": "açtı", "gates": "kapılar", "tied up": "bağladılar", "employees": "çalışanlar", "loaded": "yüklediler", "truck": "kamyon", "heavy": "ağır", "left": "bıraktılar", "hostages": "rehineler", "locked": "kilitli", "cages": "kafesler", "escaped": "kaçtılar", "police": "polis", "found": "buldu", "split up": "bölünmüş", "arrested": "tutuklandı", "much": "çoğu", "still": "hala", "missing": "kayıp" },
    questions: [ {q:"Was it the largest cash robbery in British history?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the robbers kidnap the manager?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they pretend to be pizza delivery drivers?", a_en:"No", a_tr:"Hayır"}, {q:"Did they kidnap his wife and child at their home?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they tell him they would hurt his family if he provided no help?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they leave the hostages locked in cages?", a_en:"Yes", a_tr:"Evet"}, {q:"Is much of the money still missing?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["21_UnitedCalifornia.mp3"] = [{
    text: "The United California Bank burglary happened in 1972. A professional burglar named Amil Dinsio led the crew. They heard a rumor that President Richard Nixon had illegal money hidden in the bank. They wanted to steal it. They used dynamite to blast a hole in the roof of the bank vault. They did this on a weekend. They spent three days inside the vault. They opened hundreds of safety deposit boxes. They stole about 30 million dollars. They did a perfect job and left no fingerprints. However, they made a mistake later. They forgot to run the dishwasher in their rented house nearby. The police found fingerprints on the dirty dishes. This evidence sent the whole crew to prison.",
    dict: { "burglary": "hırsızlık", "professional": "profesyonel", "burglar": "hırsız", "named": "adında", "led": "yönetti", "crew": "ekip/takım", "heard": "duydular", "rumor": "söylenti", "President": "Başkan", "illegal": "yasadışı", "money": "para", "hidden": "saklı", "bank": "banka", "wanted": "istediler", "steal": "çalmak", "used": "kullandılar", "dynamite": "dinamit", "blast": "patlatmak", "hole": "delik", "roof": "çatı", "vault": "kasa dairesi", "weekend": "hafta sonu", "spent": "geçirdiler/harcadılar", "days": "günler", "inside": "içinde", "opened": "açtılar", "hundreds": "yüzlerce", "safety deposit boxes": "kiralık kasalar", "stole": "çaldılar", "perfect": "mükemmel", "job": "iş", "left": "bıraktılar", "no": "hiç/yok", "fingerprints": "parmak izleri", "However": "ancak", "made": "yaptılar", "mistake": "hata", "later": "daha sonra", "forgot": "unuttular", "run": "çalıştırmak", "dishwasher": "bulaşık makinesi", "rented": "kiralık", "house": "ev", "nearby": "yakınlarda", "police": "polis", "found": "buldu", "dirty": "kirli", "dishes": "bulaşıklar", "evidence": "kanıt/delil", "sent": "gönderdi", "whole": "bütün", "prison": "hapishane" },
    questions: [ {q:"Did they hear a rumor about President Nixon's illegal money?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use dynamite to blast a hole in the roof?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they spend three days inside the vault?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they steal 30 million dollars?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they leave fingerprints in the bank?", a_en:"No", a_tr:"Hayır"}, {q:"Did they forget to run the dishwasher in their rented house?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the dirty dishes send the whole crew to prison?", a_en:"Yes", a_tr:"Evet"} ]
}];
